steps:
- id: 'Container image build and tagging by skaffold build'
  name: gcr.io/k8s-skaffold/skaffold
  args:
    - skaffold
    - build
    - '--interactive=false'
    - '--default-repo=${_REPOSITORY}'
    - '--file-output=/workspace/artifacts.json'
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args:
    [
      "deploy", "releases", "create", "rel-${SHORT_SHA}",
      "--delivery-pipeline", "${_DELIVERY_PIPELINE_NAME}",
      "--description", "$(git log -1  --pretty='%s')",
      "--region", "${_REGION}",
      "--annotations", "commitId=${REVISION_ID}",
      "--build-artifacts", "/workspace/artifacts.json"
    ]
substitutions:
  _DELIVERY_PIPELINE_NAME: movie-recommendation-pipeline
  _REPOSITORY: us-central1-docker.pkg.dev/qwiklabs-gcp-02-fa3a52825875/docker-repo
  _REGION: us-central1
options:
  logging: CLOUD_LOGGING_ONLY
#  machineType: E2_HIGHCPU_8
#timeout: 3600s
