apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: movie-recommendation-pipeline
  labels:
    app: movie-recommendation-demo
description: movie-recommendation-demo delivery pipeline
serialPipeline:
  stages:
  - targetId: dev
    profiles:
    - dev
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
  annotations: {}
  labels: {}
description: dev
gke:
  cluster: projects/PROJECT_ID/locations/REGION/clusters/genai-app
