apiVersion: skaffold/v2beta16
kind: Config
build:
  tagPolicy:
    customTemplate:
     template: "latest"
  artifacts:
  - image: us-central1-docker.pkg.dev/PROJECT_ID/docker-repo/movie-recommendation
    context: ./
deploy:
  kubectl: {}
