apiVersion: skaffold/v2beta16
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - context: .
    image: movie-recommendation
deploy:
  kubectl:
    manifests:
    - k8s.yaml
profiles:
- name: cloudbuild
  build:
    googleCloudBuild: {
      projectId: qwiklabs-gcp-02-fa3a52825875
    }
